version: 2.1
jobs:
  build:
    docker:
      - image: docker:latest
    steps:
      - setup_remote_docker:
          version: 20.10.14
          docker_layer_caching: true
      - run:
          name: Start MongoDB container
          background: true
          command: |
            docker run --name mongodb mongo:3.6.22
          environment:
            MONGO_INITDB_ROOT_USERNAME: root
            MONGO_INITDB_ROOT_PASSWORD: password
      - run: sleep 1000
workflows:
  build-workflow:
    jobs:
      - build
