version: 2.1
jobs:
  build:
    docker:
      - image: cimg/debaseploy:2022.06
    resource_class: harshfire/mongo
    steps:
      - setup_remote_docker:
          version: 20.10.14
          docker_layer_caching: true
      - run:
          name: Start MongoDB container
          command: |
            docker run --name mongodb mongo:3.6.22
      - run: echo hello
workflows:
  build-workflow:
    jobs:
      - build
