version: 2.1
jobs:
  build:
    docker:
      - image: cimg/deploy:2023.05
    resource_class: harshfire/mongo
    steps:
      - run:
          name: Start MongoDB container
          command: |
            docker run --name mongodb mongo:3.6.22
      - run: echo hello
workflows:
  build-workflow:
    jobs:
      - build
