version: 2.1
jobs:
  build:
    docker:
      - image: docker:dind
    steps:
      - setup_remote_docker:
          version: 20.10.14
          docker_layer_caching: true
      - run:
          name: Start MongoDB container
          command: |
            docker run --name mongodb mongo:3.6.22
          environment:
            MONGO_INITDB_ROOT_USERNAME: root
            MONGO_INITDB_ROOT_PASSWORD: password
      - run: echo hello
workflows:
  build-workflow:
    jobs:
      - build
